# Firebase CI/CD Workflow for Pull Request Preview
# Implements industry best practices for secure and efficient PR deployments

name: Deploy to Firebase Hosting on PR

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

# Define permissions needed for GitHub Actions
permissions:
  checks: write
  contents: read
  pull-requests: write
  id-token: write # Required for security hardening

# Environment variables available to all jobs
env:
  NODE_VERSION: '18'
  CACHE_KEY: node-modules-${{ github.sha }}

jobs:
  code_quality:
    name: Code quality checks
    runs-on: ubuntu-latest
    # Only run on PRs from the same repository (not forks) for security
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint
        continue-on-error: true # Don't block preview for lint errors

  build_and_preview:
    name: Build and preview deployment
    needs: code_quality
    runs-on: ubuntu-latest
    # Only run on PRs from the same repository (not forks) for security
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    environment: preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
        env:
          NODE_ENV: development

      - name: Deploy preview to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZAKIS_ESSENCE }}
          projectId: zakis-essence
          expires: 7d # Preview URL expires after 7 days
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
