# Security Scanning Workflow for Firebase CI/CD
# Implements industry best practices for security scanning

name: Security Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  schedule:
    # Run security scan weekly on Monday at 2:00 AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

# Environment variables available to all jobs
env:
  NODE_VERSION: '18'
  CACHE_KEY: node-modules-${{ github.sha }}

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high

  code-scanning:
    name: Code Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  npm-audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Generate audit report
        if: always()
        run: |
          npm audit --json > npm-audit-report.json || true
          echo "## NPM Audit Summary" > npm-audit-summary.md
          echo "" >> npm-audit-summary.md
          echo "Full report available in workflow artifacts." >> npm-audit-summary.md

      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: npm-audit-report
          path: npm-audit-report.json

  firebase-security-rules:
    name: Firebase Security Rules Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Check Firebase Security Rules
        run: |
          if [ -f "firestore.rules" ]; then
            echo "Validating Firestore security rules..."
            firebase firestore:rules:lint firestore.rules --project zakis-essence
          fi
          
          if [ -f "storage.rules" ]; then
            echo "Validating Storage security rules..."
            firebase storage:rules:lint storage.rules --project zakis-essence
          fi
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        continue-on-error: true